### ISSUE TITLE
Bundle language resources

### ISSUE THREAD

**Issue by TinoDidriksen** [TinoDidriksen/apertium-packaging#12]
We've reached the point where an update to a single language may break multiple translation pairs, so will have to bundle matching versions.

**Comment by unhammer** [comment]
What would be a good way to do this? Just store git sha's of dependencies somewhere in the pair repo (like submodules or some other text file)?

**Comment by TinoDidriksen** [comment]
`AP_CHECK_LING` would be a good place to encode this. Instead of `AP_CHECK_LING([1], [apertium-dan])` have something like `AP_CHECK_LING([1], [apertium-dan], [0.6.0])` - for development this would merely serve as a minimum version check, but for release it could serve as exact match.

**Comment by unhammer** [comment]
Does autoconf have some sort of `currently making a release` variable we can check? (Something set by make dist, perhaps?)

**Comment by TinoDidriksen** [comment]
No, autoconf should treat it as a minimum check the whole way. The packaging system can treat it exactly. Autoconf is not involved in packaging.

**Comment by TinoDidriksen** [comment]
Implemented for Apertium languages. The bundled resources will be the highest version of `AP_CHECK_LING` or package's `debian/control`, to handle cases where `AP_CHECK_LING` doesn't mention a version.
Not yet implemented for Giella languages.
