### ISSUE TITLE
Packages and pairs pending to be published

### ISSUE THREAD

**Issue by xavivars** [TinoDidriksen/apertium-packaging#18]
- [x] ron
- [x] cat
- [x] ita
- [x] por
- [x] spa
- [x] eng
- [x] oci
- [x] fra
- [x] afr
- [x] nld
- [x] ind
- [x] zlm
- [x] ron-cat
- [x] eng-cat
- [x] ita-cat
- [x] por-cat
- [x] spa-cat
- [x] oci-fra
- [x] fra-cat
- [x] afr-nld
- [x] ind-zlm

**Comment by TinoDidriksen** [comment]
apertium-ron 1.0.0:
https://github.com/apertium/apertium-packaging/commit/e436e119789eaf7cfe166bf001ec2884441ef431
https://github.com/apertium/apertium-ron/commit/dab87f888765ff02da1f84d80a9becd746c2f022

**Comment by TinoDidriksen** [comment]
apertium-ita 0.10.5:
https://github.com/apertium/apertium-packaging/commit/368c359caada05d31272e1e89e07ce495721c0c1
https://github.com/apertium/apertium-ita/commit/ca3d82b8ea0863aea8b42d625d86d179ee0da4de

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/apertium-packaging/commit/e3f53bb53e59ba619176cc1ff5813be63e4c1c63

apertium-por 0.2.0:
https://github.com/apertium/apertium-por/commit/589bc7ac0d7a48ef1e531de7d5366d9d292ea781

apertium-spa 1.2.0:
https://github.com/apertium/apertium-spa/commit/4da1f3e26212ce140d52e1cf2e6820994f7f97c5

**Comment by TinoDidriksen** [comment]
Hm. You write stable branch, but that's not the way to do it. The master branch must be stable and release-worthy - tests and unstable features go in branches, and are then merged into master when ready for use.

I only just now noticed https://github.com/apertium/apertium-spa has a stable branch - I did not use that branch.

**Comment by xavivars** [comment]
Hey Tino, sorry about that. Please go ahead and do it from the master branch.

The master branch is also "stable": we run daily regressions, etc. But once in a while, there are some regressions (like wrong desambiguations due to new words added) detected on huge corpus that live in master, and only get fixed a couple of days later.

But every "risky" change is done in branches.

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/apertium-packaging/commit/44853b98f228c37f2813bb4a03b5f507d0c351fc

apertium-cat 2.8.0:
https://github.com/apertium/apertium-packaging/commit/e695b5b9ba5ae8c5fb5f8f47f15abc2ee802e577
https://github.com/apertium/apertium-cat/releases/tag/v2.8.0

apertium-eng 0.1.0:
https://github.com/apertium/apertium-eng/commit/a020fbb9eb2cb12ad17e15bcae5634c00cd1fc5c

apertium-oci 0.2.0:
https://github.com/apertium/apertium-oci/commit/1c00a3c64fed5382971d1343956e3cbaa75e5a35

apertium-fra 1.7.0:
https://github.com/apertium/apertium-fra/commit/20626498d189f7ee930d6d863568c039463a3bc7

**Comment by TinoDidriksen** [comment]
apertium-ron-cat 1.0.0:
https://github.com/apertium/apertium-packaging/commit/97d564795ac88a41bfefb3ae94374bbb7c63355d
https://github.com/apertium/apertium-ron-cat/commit/23d3553ca9f6053d08c040a1ea1b2db6e2372d7a
https://salsa.debian.org/tinodidriksen-guest/apertium-ron-cat

Also added to public APy instance, but doesn't work there and don't know why. Works from the nightly and release .deb package, so meh. Edit: See https://github.com/apertium/apertium-anaphora/issues/38 - I always forget null flushing is a thing.

**Comment by jaumeortola** [comment]
Hi @TinoDidriksen 
Is there any obstacle preventing the release of the bilingual dictionaries?

**Comment by TinoDidriksen** [comment]
There are no technical obstacles to releasing everything.

apertium-eng-cat 1.0.0:
https://github.com/apertium/apertium-packaging/commit/2807845bc9a9df06bc678592f671e4e1971b8376
https://github.com/apertium/apertium-eng-cat/commit/fb0d61bc1b66888c822b837c53c96debcc906918
https://salsa.debian.org/science-team/apertium-en-ca (needs renaming)

Updated public APy instance. Removed old en-ca and ca-en modes and folder.

**Comment by TinoDidriksen** [comment]
apertium-cat-ita 0.2.1:
https://github.com/apertium/apertium-packaging/commit/916853e8d0ca215662b3ba68422a1676e99f5c83
https://github.com/apertium/apertium-cat-ita/commit/b28f278841a3056c63279ee7986efed3f31a0aed
https://salsa.debian.org/science-team/apertium-ca-it (needs renaming)

Updated public APy instance. Removed old ca-it folder.

**Comment by TinoDidriksen** [comment]
apertium-por-cat 0.9.0:
https://github.com/apertium/apertium-packaging/commit/cb2a91d87d19ba5a6f306c8a9a93154464e12bd1
https://github.com/apertium/apertium-por-cat/commit/173290e7fe65e98eb15704fb683a7e141961102c
https://salsa.debian.org/science-team/apertium-pt-ca (needs renaming)

Updated public APy instance. Removed old pt-ca and ca-pt modes and folder.

**Comment by TinoDidriksen** [comment]
@xavivars @jaumeortola - https://github.com/apertium/apertium-spa and https://github.com/apertium/apertium-spa-cat default branch has changed from master to develop - undo that, and anywhere else that's done.

The default branch should be master, and the default branch must be release-worthy - it's what you get when you clone the repo, so it must work out of the box. Unstable work must be done in a non-default branch. Best to just keep the default branch master.

**Comment by xavivars** [comment]
@TinoDidriksen, I think we need two find a middle point. We need a branch that everyone commits to that is not the one that gets released. And then another one that is the releasable one. You said "master" needs to be ready to release, so we want to use "develop" as the branch we use.

**Comment by TinoDidriksen** [comment]
apertium-spa-cat 2.2.0:
https://github.com/apertium/apertium-packaging/commit/fb759ef461596e7f22cb08fd42a3bbd0c606dc72
https://github.com/apertium/apertium-spa-cat/commit/cd67aeba90aee429cbbb67d3da2d63a850da3f39
https://salsa.debian.org/science-team/apertium-spa-cat

Updated public APy instance. Removed old es-ca and ca-es modes and folder.

**Comment by TinoDidriksen** [comment]
apertium-oci-fra 0.3.0:
https://github.com/apertium/apertium-packaging/commit/2dc80803acc6efec9c9ba90d70919a787d7d0e79
https://github.com/apertium/apertium-oci-fra/commit/5af008fd2f70477292f8ae8fb621197378019e83
https://salsa.debian.org/science-team/apertium-oci-fra

Updated public APy instance.

**Comment by TinoDidriksen** [comment]
apertium-fra-cat 1.7.0:
https://github.com/apertium/apertium-packaging/commit/d03d74ce1bd65903c6772a65a7ee44b41afede61
https://github.com/apertium/apertium-fra-cat/commit/e903094d6f13d18996858233b0862d49b173aa35
https://salsa.debian.org/science-team/apertium-fra-cat

Updated public APy instance.

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/apertium-packaging/commit/1c320aaada15709ee687379784d9eab6834d7303

apertium-afr 0.2.0:
https://github.com/apertium/apertium-afr/commit/d42f0a130ffeeabeb50df9246e43378e54ea6e5f

apertium-nld 0.2.0:
https://github.com/apertium/apertium-nld/commit/c93510dce1add2305fa567e2240950f1afffbf6f

apertium-afr-nld 0.3.0:
https://github.com/apertium/apertium-afr-nld/commit/417e17b4077ee94fbbc6f4f2d7938c05110eb978
https://salsa.debian.org/science-team/apertium-af-nl (needs renaming)

Updated public APy instance. Removed old af-nl and nl-af modes and folder.

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/apertium-packaging/commit/587f2f49f8452a432f12e53cd727e8b4439e3256

apertium-ind 0.2.0:
https://github.com/apertium/apertium-ind/commit/f3cb146548204af31a51f2b73bb6b7660581fa99

apertium-zlm 0.2.0:
https://github.com/apertium/apertium-zlm/commit/6186f441543f647ec4a5eb3e822b8d519df4d55f

apertium-ind-zlm 0.1.2:
https://github.com/apertium/apertium-ind-zlm/commit/18c8c50d55bf7cd45e5f1fc4697ed1c012811e32
https://salsa.debian.org/science-team/apertium-id-ms (needs renaming)

Updated public APy instance. Removed old id-ms and ms-id modes and folder.
