### ISSUE TITLE
Pending Packages (Nordic)

### ISSUE THREAD

**Issue by TinoDidriksen** [TinoDidriksen/apertium-packaging#19]
- [x] dan
- [x] nno
- [x] nob
- [x] swe
- [x] swe-dan
- [x] swe-nor
- [x] dan-nor
- [x] nno-nob

**Comment by unhammer** [comment]
All packages just tagged in github, ready for packaging :)

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/apertium-packaging/commit/248b3b047d758937d02ca721ce1e4a6dcbf5f013

apertium-dan 0.6.1:
https://github.com/apertium/apertium-dan/commit/4ac71ec60a0cd5898e3468a4377c33bdaa02b2c7

apertium-nno 1.1.0:
https://github.com/apertium/apertium-nno/commit/1552535b91c3852b54e90f2dd9407efb391f1a9c

apertium-nob 1.1.0:
https://github.com/apertium/apertium-nob/commit/3fac774d6b3eff96e20a56ed46e9b7b3c4831f9c

apertium-swe 0.8.1:
https://github.com/apertium/apertium-swe/commit/87f4c72030cf00e10f4f42d3d225c98ea81db6c5

apertium-swe-dan 0.8.1:
https://github.com/apertium/apertium-swe-dan/commit/284f6ad1983e4d2edcc3f6a6cd1e0a2b87e44459
https://salsa.debian.org/science-team/apertium-swe-dan

apetium-swe-nor 0.3.1:
https://github.com/apertium/apertium-swe-nor/commit/9b07c79a757117dfa95b5d561d6b6f66745bd712
https://salsa.debian.org/science-team/apertium-swe-nor

apertium-dan-nor 1.4.1:
https://github.com/apertium/apertium-dan-nor/commit/703c7aab62195e33967da41af5f80c657be33b60
https://salsa.debian.org/science-team/apertium-dan-nor

apertium-nno-nob 1.3.0:
https://github.com/apertium/apertium-nno-nob/commit/374b2fe8486969f040e299c0b6d8d6757d0302bb
https://salsa.debian.org/science-team/apertium-nno-nob

Public APy instance updated with all of the above.
