### ISSUE TITLE
Is the pol-szl package missing?

### ISSUE THREAD

**Issue by hectoralos** [TinoDidriksen/apertium-packaging#22]
I'm looking to the page https://phabricator.wikimedia.org/diffusion/GCXS/browse/master/config/Apertium.yaml where there is the list of translators used by Wikimedia's Content Translation. As far as I see, there is one (and only one) recent Apertium translators, not listed in issue #18, that is missing: Polish → Silesian (pol-szl). Is there a problem in packaging?

**Comment by TinoDidriksen** [comment]
It was re-pushed to Debian 3 weeks ago as https://salsa.debian.org/science-team/apertium-pol-szl and going through the new queue atm: https://ftp-master.debian.org/new.html ( https://ftp-master.debian.org/new/apertium-pol-szl_0.2.1-1.html )

So it's alive and well.
