### ISSUE TITLE
Pending packages

### ISSUE THREAD

**Issue by xavivars** [TinoDidriksen/apertium-packaging#26]
As requested by @hectoralos in the mailing list

- [x] cat
- [x] fra
- [x] por
- [x] fra-cat
- [x] por-cat

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/apertium-packaging/commit/97b54143f6da836ec482c4903fda24e6ae2e2a64

cat v2.9.0:
https://github.com/apertium/apertium-cat/commit/2758c747095e901d1c98b65a2564de8fb8811763
https://github.com/apertium/apertium-cat/releases/tag/v2.9.0

por v0.3.0:
https://github.com/apertium/apertium-por/commit/0665fb87c4a57e950adc2fb9f592f69f890bb785
https://github.com/apertium/apertium-por/releases/tag/v0.3.0

fra v1.8.0:
https://github.com/apertium/apertium-fra/commit/8052cd7c7592bafb049504e63a3f921a004ae80e
https://github.com/apertium/apertium-fra/releases/tag/v1.8.0

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/apertium-packaging/commit/b54191d08dc48a83ccbd4b0e14ae2fa741d694a0

fra-cat v1.8.0:
https://github.com/apertium/apertium-fra-cat/commit/c03ec7c1f33aa76d6cfacb3d010ef5ba45ac7b1e
https://github.com/apertium/apertium-fra-cat/releases/tag/v1.8.0
https://salsa.debian.org/science-team/apertium-fra-cat

por-cat v0.10.0:
https://github.com/apertium/apertium-por-cat/commit/7aef89b01f6b3702941e9f9ea20cab67b92434ec
https://github.com/apertium/apertium-por-cat/releases/tag/v0.10.0
https://salsa.debian.org/science-team/apertium-pt-ca
