### ISSUE TITLE
apertium core installation on kali linux

### ISSUE THREAD

**Issue by vivekvardhanadepu** [TinoDidriksen/apertium-packaging#35]
OS details:
---------------
NAME="Kali GNU/Linux"
ID=kali
VERSION="2020.4"
VERSION_ID="2020.4"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
When using apt-install-nightly.sh to install apertium core. My kali linux is detected as Xenial[You can also find in attached screenshot]. Hence getting dependency errors
![Screenshot from 2021-01-28 22-01-13](https://user-images.githubusercontent.com/32814044/106169057-f6f21580-61b4-11eb-81de-8b654b7a9e1b.png)
## Workaround
replaced "deb http://apertium.projectjj.com/apt/nightly xenial main" with "deb http://apertium.projectjj.com/apt/nightly bullseye main" in apertium.list file and it worked :grin: :grin:

**Comment by TinoDidriksen** [comment]
On a fresh Kali Rolling install, the script yields `No supported Debian or Ubuntu derivative detected - bailing out...` as it should. You must have had mixed sources for xenial to be detected.

But sure, I can add that [Kali = Debian Testing](https://www.kali.org/docs/policy/kali-linux-relationship-with-debian/).
