### ISSUE TITLE
Releases Spring 2022

### ISSUE THREAD

**Issue by TinoDidriksen** [TinoDidriksen/apertium-packaging#39]
Updated previously:

hfst 3.16.0
https://github.com/hfst/hfst/commit/3a99b739c77a22a369a51cae18c8e5eb8df0cbe4
https://github.com/hfst/hfst/releases/tag/v3.16.0
https://salsa.debian.org/science-team/hfst

foma 0.10.0
https://github.com/mhulden/foma/commit/6184b5a6fdc45082e9ff3a1f70df17574002b430
https://apertium.projectjj.com/apt/release/source/foma/
https://salsa.debian.org/science-team/foma

New releases below:

**Comment by TinoDidriksen** [comment]
cg3 v1.3.6
https://github.com/GrammarSoft/cg3/commit/25afa64a35780b7d870a6c2467a404ea67d6d23f
https://github.com/GrammarSoft/cg3/releases/tag/v1.3.6
https://salsa.debian.org/science-team/cg3

**Comment by TinoDidriksen** [comment]
hfst-ospell v0.5.3
https://github.com/hfst/hfst-ospell/commit/ed4821269e1cc57cf4281620564bc206f94b2a00
https://github.com/hfst/hfst-ospell/releases/tag/v0.5.3
https://salsa.debian.org/science-team/hfst-ospell

**Comment by TinoDidriksen** [comment]
lttoolbox 3.6.0
https://github.com/apertium/lttoolbox/commit/fcc9f0f34014329e2fb75f84489457c09d117ced
https://github.com/apertium/lttoolbox/releases/tag/v3.6.0
https://salsa.debian.org/science-team/lttoolbox

**Comment by TinoDidriksen** [comment]
apertium 3.8.0
https://github.com/apertium/apertium/commit/e450cd81cab3cfec55a8c8af529a66e54da87152
https://github.com/apertium/apertium/releases/tag/v3.8.0
https://salsa.debian.org/science-team/apertium

**Comment by TinoDidriksen** [comment]
apertium-lex-tools 0.3.0
https://github.com/apertium/apertium-lex-tools/commit/c5811060957893ce122b4bcebcf40294ea850397
https://github.com/apertium/apertium-lex-tools/releases/tag/v0.3.0
https://salsa.debian.org/science-team/apertium-lex-tools

**Comment by TinoDidriksen** [comment]
apertium-recursive 1.1.0
https://github.com/apertium/apertium-recursive/commit/0ce7d3f88b77ec19769b5cd2935ec4b7ce72aebb
https://github.com/apertium/apertium-recursive/releases/tag/v1.1.0
https://salsa.debian.org/science-team/apertium-recursive

**Comment by TinoDidriksen** [comment]
apertium-separable 0.5.0
https://github.com/apertium/apertium-separable/commit/27b8b6a55ced7d7a46ba5b23b3064d47fdf37cec
https://github.com/apertium/apertium-separable/releases/tag/v0.5.0
https://salsa.debian.org/science-team/apertium-separable

**Comment by TinoDidriksen** [comment]
apertium-anaphora 1.1.0
https://github.com/apertium/apertium-anaphora/commit/e9f5b3f3410fe5648449df173854520ecc05a1e4
https://github.com/apertium/apertium-anaphora/releases/tag/v1.1.0
https://salsa.debian.org/science-team/apertium-anaphora

**Comment by TinoDidriksen** [comment]
transfuse 0.5.8
https://github.com/TinoDidriksen/Transfuse/commit/4a3f5cd17b26df14dc99381022f70047eba79394
https://github.com/TinoDidriksen/Transfuse/releases/tag/v0.5.8
https://salsa.debian.org/science-team/transfuse

**Comment by TinoDidriksen** [comment]
lexd 1.1.0
https://github.com/apertium/lexd/commit/5ba9594a08d6e5aa0e139cacd899b9a2de911994
https://github.com/apertium/lexd/releases/tag/v1.1.0
https://salsa.debian.org/science-team/lexd

**Comment by TinoDidriksen** [comment]
Ping @kartikm - tools updated.

**Comment by TinoDidriksen** [comment]
apertium-regtest 0.9.1
https://github.com/apertium/apertium-regtest/commit/d16fd80f30e479b9d862770baa3a1917c645cb12
https://github.com/apertium/apertium-regtest/releases/tag/v0.9.1
https://salsa.debian.org/science-team/apertium-regtest - @kartikm, needs ITP in Debian

**Comment by kartikm** [comment]
> apertium-regtest 0.9.0 [apertium/apertium-regtest@a326484](https://github.com/apertium/apertium-regtest/commit/a3264842d5be28c2bdf7331a28b725b9409216fc) https://github.com/apertium/apertium-regtest/releases/tag/v0.9.0 https://salsa.debian.org/science-team/apertium-regtest - @kartikm, needs ITP in Debian

It seems it has bundled JS library - I'm sure it will create problems with the license (https://salsa.debian.org/science-team/apertium-regtest/-/tree/master/static)

**Comment by kartikm** [comment]
@TinoDidriksen See: https://salsa.debian.org/science-team/apertium-regtest/-/jobs/2559677

**Comment by TinoDidriksen** [comment]
> See: https://salsa.debian.org/science-team/apertium-regtest/-/jobs/2559677

Oh right, I totally forgot regtest bundles JS libraries for the GUI. I was only thinking about the Python code.

**Comment by TinoDidriksen** [comment]
Added workaround in 0.9.1.

**Comment by kartikm** [comment]
> Added workaround in 0.9.1.

Thanks! Is it possible to fix this also? `apertium-regtest: embedded-javascript-library usr/share/apertium-regtest/static/jquery.js please use libjs-jquery`

**Comment by TinoDidriksen** [comment]
> Thanks! Is it possible to fix this also? `apertium-regtest: embedded-javascript-library usr/share/apertium-regtest/static/jquery.js please use libjs-jquery`

That's a false positive. The Debian package does not embed jQuery - the file is just a placeholder.

**Comment by kartikm** [comment]
> > Thanks! Is it possible to fix this also? `apertium-regtest: embedded-javascript-library usr/share/apertium-regtest/static/jquery.js please use libjs-jquery`
> 
> That's a false positive. The Debian package does not embed jQuery - the file is just a placeholder.

Thanks. Uploaded to Debian experimental.

**Comment by kartikm** [comment]
@TinoDidriksen Apertium package has a few important failures: https://salsa.debian.org/science-team/apertium/-/jobs (It fails to install libttolbox and tests failures)

**Comment by TinoDidriksen** [comment]
Looks like it is trying to install the old apertium-dev 3.7.2, which naturally requires lttoolbox 3.5, which is no longer available? I'd say that's a bug in puiparts, or I don't understand what it's supposed to do.

**Comment by kartikm** [comment]
> Looks like it is trying to install the old apertium-dev 3.7.2, which naturally requires lttoolbox 3.5, which is no longer available? I'd say that's a bug in puiparts, or I don't understand what it's supposed to do.

OK. That makes sense. Autopkgtest also broken due to that?

**Comment by kartikm** [comment]
We've autopkgtest failure for lttoolbox too: https://salsa.debian.org/science-team/lttoolbox/-/jobs/2566325

**Comment by kartikm** [comment]
apertium-lex-tools has same autopkg failure: https://salsa.debian.org/science-team/apertium-lex-tools/-/jobs/2582743

**Comment by kartikm** [comment]
@TinoDidriksen Can you do new release of apertium-lex-tools also?

**Comment by TinoDidriksen** [comment]
lttoolbox 3.6.1 pushed to https://salsa.debian.org/science-team/lttoolbox

apertium-lex-tools is a bigger change, because there's now a library. Working on it.

**Comment by TinoDidriksen** [comment]
apertium-lex-tools 0.3.1 pushed to https://salsa.debian.org/science-team/apertium-lex-tools - almost no code change, but major packaging change.

**Comment by kartikm** [comment]
> apertium-lex-tools 0.3.1 pushed to https://salsa.debian.org/science-team/apertium-lex-tools - almost no code change, but major packaging change.

Thanks a lot. `W: libapertium-lex-tools0-0.3-1: package-name-doesnt-match-sonames libapertium-lex-tools0-0.3-0` probably need to fix! (ie https://salsa.debian.org/science-team/apertium-lex-tools/-/jobs/2592580)

**Comment by TinoDidriksen** [comment]
Oh, I missed that in the lintian output.

**Comment by TinoDidriksen** [comment]
apertium-all-dev 3.8.1 pushed to https://salsa.debian.org/tinodidriksen-guest/apertium-all-dev - I can't push to https://salsa.debian.org/science-team/apertium-all-dev

**Comment by kartikm** [comment]
> apertium-all-dev 3.8.1 pushed to https://salsa.debian.org/tinodidriksen-guest/apertium-all-dev - I can't push to https://salsa.debian.org/science-team/apertium-all-dev

I invited you to join the project. Can you try again?

**Comment by TinoDidriksen** [comment]
It's protected, and I apparently don't have enough rights to supercede that.
```
remote: GitLab: You are not allowed to push code to protected branches on this project.
To salsa.debian.org:science-team/apertium-all-dev.git
 ! [remote rejected] master -> master (pre-receive hook declined)
 ! [remote rejected] pristine-tar -> pristine-tar (pre-receive hook declined)
 ! [remote rejected] upstream -> upstream (pre-receive hook declined)
```

**Comment by kartikm** [comment]
Can you try again @TinoDidriksen ?

**Comment by TinoDidriksen** [comment]
That worked.
