### ISSUE TITLE
apt Certificate Verification

### ISSUE THREAD

**Issue by hendursaga** [TinoDidriksen/apertium-packaging#44]
While trying to install from the nightly Debian / Ubuntu repository, I came across this error:

```
Err:1 https://apertium.projectjj.com/apt/nightly jammy InRelease
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 144.217.254.26 443]
```

The contents of my `apertium.list` in `/etc/apt/sources.list.d/` is `deb [arch=amd64 signed-by=/usr/share/keyrings/apertium-packaging.public.gpg] https://apertium.projectjj.com/apt/nightly jammy main`

I understand this isn't top priority, since the hashes are still verified, but the SSL certificate might have expired or is failing somewhere else.

**Comment by TinoDidriksen** [comment]
Cannot reproduce:
```
$ docker run -it --rm amd64/ubuntu:jammy /bin/bash

$ apt-get -qy update
$ apt-get -qfy install wget curl
$ wget https://apertium.projectjj.com/apt/install-nightly.sh -O - | bash
$ curl https://apertium.projectjj.com/apt/install-nightly.sh | bash
```

At no point does it complain about the cert. And it shouldn't, because the cert is valid and issued by Let's Encrypt with root ISRG Root X1.
