### ISSUE TITLE
Apertium repo CentOS 8 is empty

### ISSUE THREAD

**Issue by egandariasblanco** [TinoDidriksen/apertium-packaging#47]
Hello,
We have a problem to install gp3 libraries from Apertium repository for CentOS 8. The Apertium repository in Opensuse for CentOS is not available.

https://build.opensuse.org/project/repository_state/home:TinoDidriksen:release/CentOS_8_Stream

**Comment by TinoDidriksen** [comment]
Correct. CentOS 8 Stream went EOL on 2024-05-31: https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/

I'm working on better RPM builds for supported distros.
