### ISSUE TITLE
APy incompatible with Tornado 5.0

### ISSUE THREAD

**Issue by LuccoJ** [TinoDidriksen/apertium-packaging#9]
The packages apertium-apy depends on python3-tornado (>= 3.1).

Current versions in Debian testing/sid are
```
apertium-apy:
 *** 0.10.0+g388~13c407db-1~sid1 9000
       9000 http://apertium.projectjj.com/apt/nightly sid/main amd64 Packages
python3-tornado:
     5.0.0-2 700
        700 http://ftp.debian.org/debian unstable/main amd64 Packages
 *** 5.0.0-1 800
        800 http://ftp.debian.org/debian testing/main amd64 Packages
```
Trying to "systemctl start apertium-apy" currently causes

```
systemd[1]: Started Translation server and API for Apertium.
python3[1663]: [W 180323 23:46:52 servlet:1466] Unable to import CLD2, continuing using naive method of language detection
python3[1663]: [I 180323 23:46:52 servlet:1316] 135 pair modes found
[...]
python3[1663]: [I 180323 23:46:52 servlet:1528] Serving at http://localhost:2737
python3[1663]: [I 180323 23:46:52 servlet:1540] Initialised systemd watchdog, pinging every 5000.0s
python3[1663]: Traceback (most recent call last):
python3[1663]:   File "servlet.py", line 1541, in <module>
python3[1663]:     tornado.ioloop.PeriodicCallback(wd.watchdog_ping, 1000 * wd.period, loop).start()
python3[1663]: TypeError: __init__() takes 3 positional arguments but 4 were given
systemd[1]: apertium-apy.service: Main process exited, code=exited, status=1/FAILURE
```
The help page for PeriodicCallback.__init__() states

```
 |  .. versionchanged:: 5.0
 |     The ``io_loop`` argument (deprecated since version 4.1) has been removed.
```
which I guess explains the issue.
This is probably more of a bug with APy itself, but I guess as long as the Debian packages don't depend strictly on <=4.1, it should be patched here (or else made incompatible with >4.1, temporarily breaking the packages for testing/unstable users).

**Comment by TinoDidriksen** [comment]
Unfortunately not a packaging issue. I can't require specific versions of dependencies. Packages have to work with whatever is available in the target distro, so if APy doesn't work with Tornado 4.2+ that's an APy bug. See also https://github.com/apertium/apertium-apy/pull/91 for discussion.
